name: numbers_project
description: "Flutter Project Sample"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  go_router: ^15.1.3
  flutter_svg: ^2.2.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Encode
      fonts:
        - asset: assets/fonts/EncodeSans-Regular.ttf
        - asset: assets/fonts/EncodeSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans-Thin.ttf
          weight: 200


